"""posts table

Revision ID: 7fecb8bed8df
Revises: 8c8467cabf48
Create Date: 2024-12-16 10:59:38.870037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fecb8bed8df'
down_revision = '8c8467cabf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('phone_number', sa.String(length=14), nullable=False),
    sa.Column('food_type', sa.String(length=100), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=False),
    sa.Column('food_desc', sa.String(length=256), nullable=False),
    sa.Column('donation_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_donation_date'), ['donation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_user_id'))
        batch_op.drop_index(batch_op.f('ix_donation_donation_date'))

    op.drop_table('donation')
    # ### end Alembic commands ###
